name: Try compilation

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name:
      run: make

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: outputs
        path: |
          bin/*
