name: Try compilation

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Build camera example
      run: make

    - name: Build audio example
      run: make -f Makefile.audio

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: outputs
        path: |
          bin/*
